### ISSUE TITLE
[Question] Modeling objects with spheres instead of cuboids

### ISSUE THREAD

**Issue by machur** [MIC-DKFZ/nnDetection#119]
### :question: Question

Hi @mibaumgartner, thank you for a great detection framework! 

I'm planning on using nnDetection for brain metastases detection. Since brain mets are rather spherical in appearance (in comparison to gliomas or other brain tumors) I'm wondering if using spheres instead of typical rectangular bounding boxes would improve the results. From what I've read in the nnDetection paper you tried a similar approach for circular nodules from LUNA challenge. In my opinion modeling data with spheres (with a single radius) may simplify the learning process and boost the results.

Did you compare both these approaches? Is there any existing code base for that in nnDetection/Retina U-Net repository?

**Comment by mibaumgartner** [comment]
Dear @machur,

unfortunately nnDetection is limited to produce bounding bounding boxes, there is no Code for spheres since that would inherit quite a lot of work (need to rewrite NMS, several formatting infos and IoU computations).

For LUNA we converted the spherical annotations into  segmentation masks with spheres inside them. With those, we trained RetinaU-Net where the segmentation branch was trained with spherical segmentations and the detection branch with boxes. Generally speaking, this seems to work quite well for several problems where no precise segmentations are available. 

Modelling data with spheres is indeed something interesting and is not part of nnDetection due to engineering reasons. There are some publications which experiments with detection networks with circles/spheres as output and seem to work quite well. Personally, I never worked with one of them though, so my knowledge is only limited to what was written in the respective papers.
