### ISSUE TITLE
[Question] Swap of axes (x / y / z) in the output boxes 

### ISSUE THREAD

**Issue by MMRohe** [MIC-DKFZ/nnDetection#142]
Hello,

I have ran a traning experiments with 3d data which were given in .nii.gz format. with typical shape of 512 x 512 x 20 in X / Y and Z (slice) axes.

Looking at the predicted boxes, they seem to make sense when considered under the following format : **[ zmin, ymin, zmax, ymax, xmin, xmax]** whereas my understanding is that the results should be instead in the format : **[ xmin, ymin, xmax, ymax, zmin, zmax]**

- Is it something expected from the code ?
- Do you know what could be the origin of this swap of axes between X and Z ? Does the code expect the .nii.gz file to be formatted a specific way ?
- Do you think that this could impact the performance of the code ? (ie. are there "slice / Z" specific processing applied that make it important to have the correct order of dimension during training / evaluation ?)

Thanks a lot for your help

**Comment by mibaumgartner** [comment]
At which point did you check the predicted boxes? The final result of the pkl file in the `val_predictions` folder should be in the original axes order, so given an image x,y,z, it will be in x_min, y_min, x_max, y_max, z_min, z_max

The same principle applied for different cases as well, given an z,y,x image it will produce z_min, y_min, z_max, y_max, x_min, x_max boxes in the end.

There are some notes: Internally nnDetection transposes data into the x,y,z format (assuming z is the axis with the highest spacing). All operations inside the neural network are axes independet, i.e. as long as it is configured correctly it doesn't matter where the z axis is => e.g. the docstrings were written at an earlier point and might be confusing since they assume x,y,z inputs

**Comment by MMRohe** [comment]
Thanks for your answer @mibaumgartner 

We see them in the predicted boxes indeed in val_predictions. Investigating a little bit there seems to be a swap between the data in the folder "raw-splitted" and "raw_cropped", eg.:
- in the folder "raw-splitted" data are in .nii.gz format and when loaded (with nibabel) correctly show a shape of 270 x 270 x 24
- in the folder "raw-cropped" data are in npz format now show a shape of 4x 24 x 270 x 270 (i guess including the 3 input sequences + the segmentation)
- in the folder "preprocessing" data are in npy format now show a shape of 3x 24 x 270 x 270

Once again if you do not think this swap could cause any issue with the training procedure I would not bother too much, but if you have an idea of where that can come from I would be interested to know !

Thanks again

**Comment by mibaumgartner** [comment]
Thank your for your detailed response @MMRohe,
the confusion arises from a rather awkward sitk convention and nnDetection uses sitk throughout it's whole pipeline. The produced box coordinated refer to the array obtained when load the image with Simple ITK and calling "GetArrayFromImage". That function inverts the axis order when compared to other readers such as nibabel which results in the inverted axis. 

So to align the produced coordinates with your images when using nibabel you need to switch around the axis as you have specified in your first comment. Everything else inside nnDetection will work just fine :)
