### ISSUE TITLE
cross validation split

### ISSUE THREAD

**Issue by EvelyneCalista** [MIC-DKFZ/nnDetection#145]
hi @mibaumgartner ,

I got this warning when training the fold-0 which there is no positive sample, since my data is imbalance, i would like to to stratify split k-fold. however i cannot find the code line to split the cross validation. May I know how can I do stratify kfold for training?

_/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_ranking.py:811: UndefinedMetricWarning: **No positive samples in y_true**, true positive value should be meaningless
  warnings.warn("No positive samples in y_true, "_

Thank you for your help.

**Comment by mibaumgartner** [comment]
hi @EvelyneCalista, you can always manually create a "splits_final.pkl" in the preprocessed directory of your data to define custom splits. However note: Since we are in object detection, the warning can have different meanings and does not automatically mean that there are not objects in your current validation. If the model is still at the beginning of the training phase it might not detect any object and thus leading to no positive samples on the object level evaluation.

**Comment by EvelyneCalista** [comment]
hi @mibaumgartner , 

thank you for your fast response and help. 
I understand now, I got wrong concept for positive & negative samples and it looks like i can ignore the warning since it is in the first epoch. 
sorry for the inconvenience, I am a beginner in object detection therefore I have lot of questions and confuses.

Thank you again
