### ISSUE TITLE
[Question] big object across patches

### ISSUE THREAD

**Issue by jjjcs** [MIC-DKFZ/nnDetection#147]
### :question: Question

Thanks for your great works. Im trying to detect the spine area in CTs. There should be only one bbox in a single CT, and the bbox is so big that is must lay across different patches. As a result the spine is detected with several bboxes. I think this might be an inherent disadvantage of patch based model against big object across patches, i need to do some postprocess to the resulted bbox. Apart form the postprocess, is there any thing i can do during the training to solve this problem?
![image](https://user-images.githubusercontent.com/64267773/220258576-777ec93b-c21b-431b-a231-ed4a4e2cc0ef.png)

**Comment by mibaumgartner** [comment]
Dear @jjjcs ,

you are absolutely right, detecting extremely large objects (i.e. objects that significantly exceed the patch size of nnDetection) is currently one of the shortcomings of our method/configuration and quite hard to fix. I think there are several ways of approaching the problem:

1) Since this is not a typical detection problem, i.e. most/all people have exactly one spine so the number of objects is known a priori, potentially running a segmentation model (there are even public datasets with spine annotations) and performing simple post-processing (keep the largest connected component) might be the easiest choice for this problem.
2) Another approach would be to manually downsample the scans first so the field of view of nnDetection is increased even further. The standard downsampling of the low res model is 2x but something like 4x could be used in this case as well.
3) Perform additional post-processing to merge the box predictions.

Best,
Michael

**Comment by jjjcs** [comment]
after some attempts, i still cant find why there are some false negatives with such high score. I am not sure what do you mean "with the ensemble after the entire training", but i have set the --sweep parameter when training. And after the training, i also consolidate the model just like your guidance.
Is that possible the model is overfitted? i should reduce the training epoch?

**Comment by jjjcs** [comment]
after some attempts, i still cant find why there are some false positives with such high score. I am not sure what do you mean "with the ensemble after the entire training", but i have set the --sweep parameter when training. And after the training, i also consolidate the model just like the guidance.
Is that possible the model is overfitted? i should reduce the training epoch? But the train loss curve seems good for me
![image](https://user-images.githubusercontent.com/64267773/228102571-9d196385-7f22-4154-aa3c-2cb05d050d4a.png)
