### ISSUE TITLE
[Question]torch._six

### ISSUE THREAD

**Issue by Zhang-JnQn** [MIC-DKFZ/nnDetection#168]
### :question: Question

Hey:
    When I run ```nndet_prep``` , it comes to be like this:
    ModuleNotFoundError: No module named 'torch._six'
    As I know Torch does not seem to support torch._six anymore and it has been removed.How can I deal with it?

**Comment by yl3639** [comment]
install pytorch with compatible cuda version.
For me,
run conda list pytorch and there is only pytorch-lightning instead of pytorch.
So i run
conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.2 -c pytorch -c conda-forge
and then error gone, nndet_example can be runned.

**Comment by yl3639** [comment]
> 
install pytorch with compatible cuda version.
For me,
run conda list pytorch and there is only pytorch-lightning instead of pytorch.
So i run
conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.2 -c pytorch -c conda-forge
and then error gone, nndet_example can be runned.

**Comment by Zhang-JnQn** [comment]
Thanks, I will try it.

**Comment by Zhang-JnQn** [comment]
@yl3639 It works for me. Thanks a lot.
