### ISSUE TITLE
[Question] what does sweep actually do

### ISSUE THREAD

**Issue by yl3639** [MIC-DKFZ/nnDetection#176]
### :question: Question

Hi may I ask what does sweep actually do?
<img width="478" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/04f082a6-92fe-4373-945a-3faad852543b">

<img width="1894" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/8b1d0199-d301-4c83-b962-e5d8f65dd79a">

<img width="915" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/64fecad7-6c00-4346-bcd8-5d9a2d581593">

I see it loaded last model while I think and i hope it will load the best model, how can i modify?

**Comment by mibaumgartner** [comment]
Hey,

loading the last model is the expected behaviour since (by default) we train for a fixed amount of time. It is possible to change the behavior by adding/modifying the 'sweep_ckpt' in the trainer_cfg and setting it to 'best'.

https://github.com/MIC-DKFZ/nnDetection/blob/98eb97f15d9f9d107fac11d27c153e18932ab635/nndet/ptmodule/retinaunet/base.py#LL765C21-L765C21

Best,
Michael

**Comment by yl3639** [comment]
> Hey,
> 
> loading the last model is the expected behaviour since (by default) we train for a fixed amount of time. It is possible to change the behavior by adding/modifying the 'sweep_ckpt' in the trainer_cfg and setting it to 'best'.
> 
> https://github.com/MIC-DKFZ/nnDetection/blob/98eb97f15d9f9d107fac11d27c153e18932ab635/nndet/ptmodule/retinaunet/base.py#LL765C21-L765C21
> 
> Best, Michael

Thanks for reply!
May I ask what does the json file under /Task/RetinaUNetV001_D3V001_3d/fold0/sweep do?

<img width="930" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/1c6c76e1-59b9-4713-ba07-63619dee332a">

**Comment by yl3639** [comment]
Hi, I write my own prediction file by extracting the prediction parts in the nndet/scripts/predict.py. My plan was to use the model_best.pth in the training directory and predict on any cases.

<img width="860" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/2944df28-e592-4715-b378-7fcf08548030">

but the results i ran using the my prediction code are different compared with the results at /training_directory/fold0/val_predictions/ by running nndet_sweep XXX 0, is there any problem with the code? Thanks for help!

<img width="389" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/3fe06464-79fa-4d2c-afe4-d65330724af2">

<img width="416" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/afbdea97-0c83-48b8-83bf-d9d85be18cde">

**Comment by mibaumgartner** [comment]
There can be some deviations between reruns of the prediction pipeline due to numerical issues with floating point numbers, determinism etc. In general the pipeline looks ok but a more through check with intermediate steps would be required.

**Comment by yl3639** [comment]
Besides, may i ask what does the crop and transform do during preprocessing? It takes a 4~5 mins per case so as the prediction process may be too long.
<img width="1904" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/2d5ae351-582d-4561-a64d-6a4493db8512">
<img width="312" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/9e75c78e-c9c6-4c93-bde5-0968d620fab7">

For my situation, my case doesn't have cropping(size remain the same after cropping) and resampling(all cases are resampled to (0.4, 0.4, 0.4) in advance) needs, for transform, what does the transform do in nndetection? For intensity, usually I would just do a window clip and normalize intensities to 0~1, is there any other transform requirements required from the nndetection? To accelerate the prediction process, I think I should simplify the preprocessing process. Thanks!

**Comment by mibaumgartner** [comment]
The cropping removes areas where only 0's are located. The resampling is performed to make sure that the test data has the same spacing as the training data, since it was resampled as well. The test data needs to have the same format as the training data! - no previous resampling or normalisation should be applied to it otherwise additional cofounders are introduced. nnDetection performs cropping, resampling and intensity normalisation. The intensity normalisation type and resampling spacing depend on the presented data.
