### ISSUE TITLE
low resolution scheme

### ISSUE THREAD

**Issue by vankhoa21991** [MIC-DKFZ/nnDetection#18]
Hello, I have some questions about the low resolution scheme:

1/ When it is generated?
2/ How it's used later in training and validation?

Thanks for your help,

Van Khoa

**Comment by mibaumgartner** [comment]
Hi @vankhoa21991 ,

1) The trigger can be found here: https://github.com/MIC-DKFZ/nnDetection/blob/470ef323f90f14e120547d326bce46c5f90a9893/nndet/planning/experiment/v001.py#L186-L210
It is triggered if the 99.5 percentile of box sizes exceed the patch size.

2) The models are trained separately and the best model according to the validation results should be used for the final inference/prediction stage (currently, this is done manually by simply checking the validation score). In the current pool of data sets, this only happens for Kits19 since the tumors are quite large there.
This approach also has its downsides since the low-resolution model might miss small objects while the full-resolution model can not capture large objects accurately. A better solution to this problem might be interesting for the future ;)

Best,
Michael
