### ISSUE TITLE
[Question]Question about "Taming Detection Transformers for Medical Object Detection"

### ISSUE THREAD

**Issue by shiontao** [MIC-DKFZ/nnDetection#186]
Hello,
I'm very interested in your team's publication "Taming Detection Transformers for Medical Object Detection". Are all the detectors mentioned in the paper 3D? The description of the method in the paper seems a bit vague. Do you have any plans to open source this in the near future?
Thank you.

**Comment by mibaumgartner** [comment]
Dear @shiontao ,

yes, all of the detectors in the paper were implemented as 3D networks and predict 3D boxes. Due to the page limitations we couldn't go into too much details in the paper but we are happy to answer any open questions.

The models were implemented in a separate project and we are currently working on integrating them into nnDetection. We are planning to open source the models in a future release of nnDetection but that will still take quite a lot of time.

Best,
Michael

**Comment by shiontao** [comment]
Thank you for your prompt reply!
