### ISSUE TITLE
Resample mask error

### ISSUE THREAD

**Issue by vankhoa21991** [MIC-DKFZ/nnDetection#19]
Hello, I reveived this warning and error in the preprocessing stage. This is due to the resample process that make some instances disappear?

2021-07-19 15:06:43.138 | WARNING  | nndet.planning.properties.instance:instance_class_and_region_sizes:213 - Instance lost. Found {1: 0, 2: 0, 3: 0, 4: 0} in properties but [1 2 3] in seg of 1_2_840_113654_2_55_446543879.

Thanks

**Comment by vankhoa21991** [comment]
When I read the code, it seems like at this stage the only thing was done is to read image and save back to npz, so what cause is the reason of instance missing??

**Comment by mibaumgartner** [comment]
Hi @vankhoa21991 ,

can you double check that specific case for any anomalies (e.g. wrong segmentation mask, wrong label json, data corruption due to an error during a copy process)? Since the warning is raised in the analysis phase no resampling was performed until that point. The case was only cropped to the non-zero regions so all instances should be present during analysis. (Sometimes if the data is corrupted, large regions of the scan were zero and thus disappeared in the cropping stage).

You are right that small objects can vanish during the resampling phase though (and that also happens sometimes). The message looks different then and can be found here https://github.com/MIC-DKFZ/nnDetection/blob/470ef323f90f14e120547d326bce46c5f90a9893/scripts/preprocess.py#L347-L350.


Best,
Michael
