### ISSUE TITLE
[Question]Is it possible to use other backbones?

### ISSUE THREAD

**Issue by liuaohanjsj** [MIC-DKFZ/nnDetection#190]
### :question: Question

By default nnDetection use a RetinaNet as a backbone. I am wondering if one can replace the backbone with another network, e.g., Swin Transformer?

**Comment by mibaumgartner** [comment]
V1 of nnDetection only includes the provided plain convolutional backbone. It is however possible to implement additional backbones by yourself which can be either self-configuring or "static". Note: If your backbone is not self configuring it still needs to produce the expected feature map sizes of the plan, otherwise the detector won't work correctly (likely an error is thrown).
