### ISSUE TITLE
Relevance of masks in training a nnDetection model for nodule detection

### ISSUE THREAD

**Issue by DSRajesh** [MIC-DKFZ/nnDetection#211]

**Comment by DSRajesh** [comment]
Hello,   

Assuming that we want to train a model for cancer nodule detection, and also, we want to use a dataset other than LIDC (say LNDb): 
 1.  How do we prepare the dataset for training.  We don't have the contour coordinates specified for LNDb as is the case for LIDC.    
 2.  Is it important that we merge the planar surfaces of ROIs in order to get the ground truth values?   
 
3. Or can we approximate an ellipsoid just fitting the cuboid encompassing the nodule and hence obtain the ground truth values?     

Thanking you

Rajesh

**Comment by mibaumgartner** [comment]
Hello @DSRajesh ,

1) Yes, it is definitely possible to approximate the nodules with elipsoids to train nndetection and the results will still be suitable - this is also what we have done for LUNA16. In some instance the segmentations could overlap (since boxes can overlap too) which need a manual strategy to be resolved. 
There might some conflicting gradients when training with a mixture of exact segmentations and rough segmentation. This problem didn't come up for me yet so it is hard to comment on the exact performance degradation. I would experiment with different settings, e.g. train a model only on the subset with exact segmentation, train a model with a mixture of the annotations etc. and check their performance in the 5 Fold CV setting.

2) As I have described above, there is certainly some influence in the segmentation part of the model, and the multi-task learning might influence the detection performance as well. Also, there are differences with the augmentations; e.g. rotating an approximate structure and getting its axes aligned box introduces some errors in the training boxes. In case of exact segmentations, Retina U-Net outperformed its box-only counterpart (RetinaNet) consistently. Furthermore, there are multiple papers that used a segmentation approximation and showed improved results. I haven't seen literature where exact segmentations and approximations were mixed together. 

Best,
Michael
