### ISSUE TITLE
Training Parameter

### ISSUE THREAD

**Issue by efox94** [MIC-DKFZ/nnDetection#213]
Hello,

Can you briefly inform about the the number of epochs, criteria for stopping training, and the methodology for determining optimized hyperparameters in nndetect?

Best,

**Comment by mibaumgartner** [comment]
Dear @efox94 ,

nnDetection trains for 50 "normal" epochs and 10 epochs with SWA (Stochastic Weight averaging). It will always train a fixed number of epochs, no stopping criterion.

Can you elaborate which parameters you are specifically looking for? Otherwise, our paper should contain all/most of the information you are looking for.

Best,
Michael
