### ISSUE TITLE
issues related to resolution  at which nnDetection training is to be carried out

### ISSUE THREAD

**Issue by DSRajesh** [MIC-DKFZ/nnDetection#216]
Hello

1. How is the resolution at which nnDetection models that are trained obtained ? Is it the median spacing in the dataset.
2. Will choosing the median spacing be adverse ? (We have a lot of ground truth data including data from scanners as far back as 15 years. This would make the median resolution fairly coarser than what current scanners are capable of). In other words inference on newer generation data will effectively downsample it to the median (coarser) spacing and detection is done at coarser resolution than the data that was acquired ?
3. How can we specify a custom resolution instead of the median ?

Thanking you

Rajesh D S

**Comment by mibaumgartner** [comment]
Dear @DSRajesh ,

(1) yes, the spacing is the median spacing of the dataset
(2) the implicit assumption in nnDetection/nnU-Net (and general ML) is that your training data reflects your inference/testing data, otherwise you have a distribution shift / domain gap. If you assume that the model is primarily applied to new images (with smaller spacing) it would make sense to use a different rule/manually set the spacing to reduce the domain gap between training and testing. In general, one might need to check how beneficial the old data actually is for the training and if it helps with newer data as well. 
(3) You can set the target spacing manually here: https://github.com/MIC-DKFZ/nnDetection/blob/b2e0e4829f4dd9662a2ea7df219a658589716f57/nndet/planning/experiment/v001.py#L125-L184

Best,
Michael

**Comment by Rajesh-ParaxialTech** [comment]
> Dear @DSRajesh ,
> 
> (1) yes, the spacing is the median spacing of the dataset (2) the implicit assumption in nnDetection/nnU-Net (and general ML) is that your training data reflects your inference/testing data, otherwise you have a distribution shift / domain gap. If you assume that the model is primarily applied to new images (with smaller spacing) it would make sense to use a different rule/manually set the spacing to reduce the domain gap between training and testing. In general, one might need to check how beneficial the old data actually is for the training and if it helps with newer data as well. (3) You can set the target spacing manually here:
> 
> https://github.com/MIC-DKFZ/nnDetection/blob/b2e0e4829f4dd9662a2ea7df219a658589716f57/nndet/planning/experiment/v001.py#L125-L184
> 
> Best, Michael

Hello Micheal

Thanks a lot.  I need some clarification regarding specification of the target_spacing.  Suppose I want to specify   xspacing, yspacing, zspacing  =0.75, 0.75, 0.75. Can I specify it as follows:

![image](https://github.com/MIC-DKFZ/nnDetection/assets/159233894/b20f4222-404c-4daf-bffe-d7a726b1d9ce)



or it must be  like follows:



![image](https://github.com/MIC-DKFZ/nnDetection/assets/159233894/767626e8-0809-4c28-913e-88cde660f947)


please let me know.


Thank you
Rajesh

**Comment by mibaumgartner** [comment]
Dear @Rajesh-ParaxialTech ,

the target spacing returned by that function corresponds to the spacing your data is in -> nnDetection transposes the axes at a later point (see linked code below) to unify it.
https://github.com/MIC-DKFZ/nnDetection/blob/8032b8d2d4366ce0c3812ce96f747b443fa2f080/nndet/planning/experiment/base.py#L225

If 'transpose_forward" is [0, 1, 2] the target spacing [1.0, 0.75, 0.75] is correct. If the transpose forward moves the last axes to the front (e.g. transpose forward [2, 0, 1]) than [0.75, 0.75, 1.0] is correct.

Best,
Michael

**Comment by Rajesh-ParaxialTech** [comment]
Thanks Michael
