### ISSUE TITLE
coordinates of bounding box of nodules

### ISSUE THREAD

**Issue by DSRajesh** [MIC-DKFZ/nnDetection#218]
Hello
I have a doubt regarding the discussion in   

https://github.com/MIC-DKFZ/nnDetection/issues/132.

![image](https://github.com/MIC-DKFZ/nnDetection/assets/60175495/d664280e-8c9d-4698-929e-261e979ec781)
How can zmin,  zmax  take values    144, 199  respectively when there just 82 slices as shown in the  question below

![image](https://github.com/MIC-DKFZ/nnDetection/assets/60175495/ad868109-0239-431d-9044-1aaa797dd573)

The ordering of the coordinates must be like         zmin, ymin, zmax, ymax, xmin, xmax             right ?

Also why the ordering is like this if it is so ?

Thank you
Rajesh

**Comment by mibaumgartner** [comment]
Dear Rajesh,

the format is always a bit tricky due to sitk.. 

In the following examples the axis ordering can be interchanged arbitrarily and all the predictions will follow the relativ orderings (that is why I prefer to use ax0, ax1, ax2 instead of the typical x,y,z .. ) 

Nifty Ordering of the Image/sitk image: z,y,x
Array ordering (after GetArrayFromImage): x,y,z
Predictions: x_min, y_min, x_max, y_max, z_min, z_max

In the above example (in the image):
Nifty ordering (not shown): x,y,z
Array ordering (this is seen in 'original_size_of_raw_data'): z,y,x
Predictions: z_min, y_min, z_max, y_max, x_min, x_max

-> note how the indices of the predcitions always follow the ordering of the array format; the first 4 entries reference the first two axis of the image and the last two entries refer to the last axes of the image

As indicated in my comment in the original post: **given an image**  (I meant array there) **in x,y,z format**  
The arrows in your post show from x,y,z predictions to an z,y,x array. 

(hope this makes sense 😅 )

Regarding the format: 
The x_min, y_min, x_max, y_max format is commonly used in object detection frameworks in the natural image computing domain. The reason to extend it in the way we did it, is code reuse from the natural image computing domain -> this allows for a simple extension of the third dimension without needing to rewrite entire functions.
