### ISSUE TITLE
[Question] Negative Loss 

### ISSUE THREAD

**Issue by laurenznagler** [MIC-DKFZ/nnDetection#239]
### :question: Question

Hi I am currently trying to train the model on self annotated data. Unfortunately the loss always tends to become negative and the results are very poor. Do you have an idea why this could be the case? The data is just a segmentation of fracture in some bone, it's just one class so there is no instance segmentation mask. 

BR Laurenz :)

**Comment by mibaumgartner** [comment]
Hi,

1) it is normal that the loss becomes negative since nnDetection skips some of the +1 additions to keep the loss positive - the optimization remains the same (e.g. Dice, GIoU loss)
2) What do you mean by "just a segmentation of fracture"? e.g. Can there be multiple fractures at different positions? An instance segmentation can also contain multiple instances of the same class which need to be assigned different ids - otherwise there is not way to differentiate the different instances from each other. 
3) Are the fractures very large and the low res stage is needed to enclose them in a box within a single patch? What is the patch size determined by nnDetection?

Best,
Michael

**Comment by laurenznagler** [comment]
Hi thanks for the fast reply!

1. Ah ok i see i thought there was something wrong with the labelling of the data maybe. 
2. There is at most one fracture visible per slice. 
3. Where would i be able to find this? The fractures are compared to the slice dimension (512 x 512) rather small. In the the file `train.log` i found this: Loading network patch size [128 192 128] and generator patch size [295, 328, 249].

Maybe for further information, i use this config: 

```
{
    "name": "ForeArm",
    "task": "Task123_ForeArm",
    "target_class": null,
    "test_labels": false,
    "labels": {
        "0": "fracture"
    },
    "modalities": {
        "0": "CT"
    },
    "dim": 3
}
```

with this:

```
{
    "instances": {
        "1": 0
    }
}

```
for each sample.

**Comment by mibaumgartner** [comment]
The patch size looks good to me (I thought maybe something is off there ;) ) 

"There is at most one fracture visible per slice." -> Is it really slice or scan? 
If multiple fractures can occur within the image an instance segmentation (or at least connected components to derive instances) is needed. Otherwise the derived objects are wrong, e.g.

Consider the following example:
If fracture one is in the top left of the image, fracture two is in the bottom right and both fractures have the same number inside the segmentation (i.e. they are treated as the same instance) ==> the derived bounding box will span the entire image which is wrong.
"Image" refers to the whole 3D (CT/MRI) volume, not an individual slice. nnDetection is build to process 3D volumes and thus is uses 3d patches & networks.

**Comment by laurenznagler** [comment]
Ok initially i had the same concern.. What i mean is that per scan (3D volume) only one fracture, which spans throughout multiple slices, is visible. So if you were to look at an individual slice you would at most see one fracture.

**Comment by mibaumgartner** [comment]
Okey, than a single instance in the segmentation is the correct approach - since there is only a single fracture in the entire volume (it doesn't matter if it spans multiple slices). 

How do you currently quantify "poor results"? Are the boxes inaccurate, are many fracture missed completely etc. ? What is the AP @ IoU0.1 and FROC @ IoU0.1 in the `val_results` folder?

**Comment by laurenznagler** [comment]
I interrupted the training for the different folds at some point, as during training the achieved metrics were very low and limited resource access. 

mAP@0.1:0.5:0.05: 0.122  AP@0.1: 0.298  AP@0.5: 0.006
Proxy FG Dice: 0.190

I could rerun everything and report more precice results after the training ise finished.

**Comment by laurenznagler** [comment]
I stopped training after 15 epochs. The dataset contains roughly 30 volumes with fractures.

**Comment by laurenznagler** [comment]
Hi, i retrained for 25 epochs and i can report the following values in the `val_results` folder: 
```
AP_IoU_0.10_MaxDet_100": "0.39791311179794886
FROC_score_IoU_0.10": "0.4047619047619047
```

For reliable inference I would expect higher values. Do you think there is a problem with the data or the configuration files of the training? I cannot really think of any other problem as I reproduced good results on e.g. RibFrac.

BR and have a nice weekend,
Laurenz :)

**Comment by mibaumgartner** [comment]
The results seems rather low indeed, until now I have never tested nnDetection on datasets <100 objects. Even 100 objects is already quite at the low end of the spectrum which I would recommend. Usually aiming for at least ~300 objects in the dataset is a good reference value. (at least without exploring more sophisticated techniques like transfer learning which is currently not supported natively)   

There could also be other factors, e.g. objects are very large and do not fit into a single patch which hampers performance significantly -> I don't really think this is the case here though.

**Comment by laurenznagler** [comment]
Ok thanks a lot, I will try to acquire more training samples in that case. If I manage I'll report back!
