### ISSUE TITLE
[Question] Impact of empty GT

### ISSUE THREAD

**Issue by Thibescobar** [MIC-DKFZ/nnDetection#252]
Hello,

I'm wondering what to do with datasets where a proportion of samples has nothing to be detected (eg, no lesion). 

Should I include this data with empty label maps (so that the model learns the background better?)? 
Or should I exclude this data because we still need at least one item to detect? 
Or does it make no difference?

Thanks in advance for your advice.

**Comment by mibaumgartner** [comment]
Dear @Thibescobar ,

yes, I would generally recommend to include healthy/negative cases in your dataset as well. While positive cases also provide background information during training (due to the patch based sampling) there can always be other changes in not annotated structures which might differ between a negative and positive case. 

In previous studies we have also observed, that detection networks are far less likely to make mistakes (FP) in negative cases rather than in positive ones.

Best,
Michael

**Comment by tbskbr** [comment]
Thank you very much !
