### ISSUE TITLE
[Question] Instance Lost and Key error

### ISSUE THREAD

**Issue by NataliaAlves13** [MIC-DKFZ/nnDetection#257]
### :question: Question
I'm running the planning step nndet_prep and keep getting versions of this warning for different images:
WARNING  | nndet.planning.properties.instance:instance_class_and_region_sizes:217 - Instance lost. Found {1: 0, 2: 0} in properties but [1] in seg of xxx.
However when I check the label nifti and json in the raw_cropped and raw_splitted folders they match each other and don't match with the warning message. For instance in this case the json file states only {1:0}.
Later in the process I get the following key error:

Traceback (most recent call last):
  File "/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/nnDetection/nndet/planning/properties/instance.py", line 162, in analyze_instances_per_case
    instance_class_and_region_sizes(case_id, iseg, props, all_classes)
  File "/nnDetection/nndet/planning/properties/instance.py", line 222, in instance_class_and_region_sizes
    i_cls = instance_classes[instance_id]
KeyError: 1

Could this error be related to the warnings above? What could be causing the warnings in the first place? Any help would be much appreciated!

**Comment by mibaumgartner** [comment]
Dear @NataliaAlves13 ,

did you run the code with multiprocessing? In this case the case id printed before might not correspond to the sample that is actually causing the error.

If the 'full_check' of the preprocessing does not raise any error (full enable it to automatically check that everything is consistent) this is usually caused by removing an instance during the cropping stage. From my experience this only happens in two cases:

(1) the annotation is somewhere where it shouldn't be: the cropping removed zero areas, usually air around brain MRIs, and the instance was located somewhere wrong there
(2) one of the images got corrupted (this may happen when copying nifites..) and suddenly there is a large zero area which gets removed in the cropping stage -> instance is suddenly missing.

**Comment by NataliaAlves13** [comment]
It was indeed a problem with a corrupted file. Thank you for the help!
