### ISSUE TITLE
[Bug]preprocess the LUNA_16 dataset encountered an error 

### ISSUE THREAD

**Issue by aiaini66** [MIC-DKFZ/nnDetection#258]
![error_report](https://github.com/MIC-DKFZ/nnDetection/assets/27721212/9d0dba56-253a-4045-bf40-8cdcc4b0c97e)
### :skull: Bug

I printed the variable values at the error location，and found it is the sizes = 0 cased .

### Environment
Please provide some information about the used environment.
I installed the environment through source.

How was nnDetection installed [`docker` | `source`]:

Environment Information:
```text
[paste here]
```

If necessary, please provide the used run command with all overwrites:
```text
[paste here]
```

**Comment by mibaumgartner** [comment]
Dear @aiaini66 ,

something seems to go wrong during the estimation since the code tries to estimate the memory of a patch size of size `3,8,7`. As you can see in the screen shot a different error is caught during the optimisation: "CUDDN_STATUS_INTERNAL_ERROR" which indicates a different problem. 

Best,
Michael

**Comment by aiaini66** [comment]
thank you very much !
