### ISSUE TITLE
Prediction Results Vary Significantly with Same Dataset and Weights in nnDetection

### ISSUE THREAD

**Issue by kimm51** [MIC-DKFZ/nnDetection#262]
Hello,

I trained my dataset with nnDetection last year and tested it with different datasets. Now, I need to test more datasets (the labelTs is the same, just testing the different reconstructed images). Here is the process I followed:

1. I copied my pretrained nnDetection folder.
2. In the nnDetection folder, I removed the imagesTs in the det_data/Task100_MeniscusTear/preprocessed/D3V001_3d folder.
3. I ran the following command: "sudo docker run --gpus all -v /home/fh/nnDetection/det_data:/opt/data -v /home/fh/nnDetection/det_models:/opt/models -it --shm-size=24gb nndetection:0.1 /bin/bash"
4. Inside the Docker container, I executed: "nndet_predict 100 RetinaUNetV001_D3V001_3d --fold -1"

However, when testing the previous dataset, the prediction results were significantly different from the last prediction, despite using the same dataset and weights. For example, when I used a dataset with 45 samples, the prediction gave me 103 results (which is count of my first fully sampled test scans), but my dataset consisted of a different sample count. I did not face this problem last year.

Please inform me about the possible reasons for this discrepancy, as it seems impossible with the same dataset and weights.

Thank you.

**Comment by mibaumgartner** [comment]
Dear @kimm51 ,

some slight differences in the predictions on the same data with the same model are to be expected since some of the operations are not fully deterministic, examples are:
(1) ranking is not clearly defined if the predictions have the same score; this has an influence on the selection of the topk highest scoring predictions and sorting during evaluation
(2) model execution on the GPU is not deterministic which results in very slight deviations in predictions and might result in slightly different clusters
The differences between runs should however be very minor.

Can you specify "vary significantly" more precisely in your context?
- I don't quite understand what you mean by "For example, when I used a dataset with 45 samples, the prediction gave me 103 results (which is count of my first fully sampled test scans), but my dataset consisted of a different sample count." 
- What is a "result" in this context - do you mean there are 103 predicted boxes across your whole dataset or do you mean you received 103 prediction files from the 45 samples? 
- What is a sample in this context? Is it a single image? 

Could you also provide the log of the prediction?

Best,
Michael

**Comment by kimm51** [comment]
Hello,

Thank you for your quick response! Firstly, I want to thank you for all your support. Last year, I trained nnDetection with fully sampled MRI scans and tested it with different reconstruction network outcomes (on an RTX 4080 with 46 GB RAM in a notebook). Last year, I achieved a 0.69 mAP @0.1 Max.Det. 100, but this time, using the same dataset, the mAP @0.1 Max.Det. 100 was 0.64. However, this test was done on an RTX 2080 with 96 GB Memory in a PC.

To add novelty to this study, I wanted to test again with ZeroFilled, CGSENSE, and other networks. The results are very close to each other, and some are even lower than ZeroFilled, which is unexpected. I couldn't understand the reason because last year I did not encounter such an issue.

You asked for clarification regarding my dataset and results. When I mentioned, "For example, when I used a dataset with 45 samples, the prediction gave me 103 results (which is the count of my first fully sampled test scans), but my dataset consisted of a different sample count," I meant the following:

By "results," I am referring to the test_results across the whole dataset.
A "sample" in this context refers to a  volume.
The test dataset consisted of 45 PD and 58 PDFS pulse sequences. I intended to test only 45 PD volumes, but the prediction ran for 103 volumes, even though the imagesTs folder only included the 45 PD sequences. This inconsistency is something I did not face last year.

Best regards,

**Comment by mibaumgartner** [comment]
Dear @kimm51 ,

thank you for your kind words :) 
That is indeed quite a large difference given that the network and data is exactly the same. You could also make sure to use the same version of the code as you used in the past (assuming you might have rebuild it from the latest master), there shouldn't be any differences but just in case :) The results folders also contains prediction histograms which can be very useful for debugging such issues. 

Given that there are more predictions than images there seems to be something going on though anyway which needs to be changed. 

Could you please try again and double checking:
(1) The raw_splitted/imagesTs folder contains 45 volumes
(2) preprocessed/D3V001/imagesTs is deleted
(3) RetinaUNetV001/consolidated/test_predictions was copied somewhere as backup and deleted afterwards (otherwise it will still contain the old predictions) 

The model folder also contains a log file, "inference.log" which provides quite a lot of information about how many cases where found, which cases were predicted etc. Please check (or even better provide) the log file to check for suspicious looking case numbers. 

Best,
Michael
