### ISSUE TITLE
[Bug]Resampling should be applied to the transposed image

### ISSUE THREAD

**Issue by JiaminRen** [MIC-DKFZ/nnDetection#27]
https://github.com/MIC-DKFZ/nnDetection/blob/61d46a7fac4ed754f8c3c27709ad50dbe224ac33/nndet/inference/restore.py#L107

**Comment by mibaumgartner** [comment]
Hi @JiaminRen ,

you are right, great catch! The function is only used inside the `SegmentationEnsembler` in case the segmentation output from Retina U-Net needs to be reconstructed for a whole patient. Since we didn't use it for any of our experiments I'll mark it as an experimental feature for now.

Best,
Michael

**Comment by mibaumgartner** [comment]
Was fixed in 537a3032c6383a6faca00fe23459c32339dc09d7
