### ISSUE TITLE
[Question]Overlapping Bounding Boxes and Incomplete Boxes Issue with Pulmonary Embolism Detection

### ISSUE THREAD

**Issue by ZHUJJFDU** [MIC-DKFZ/nnDetection#277]
Hello,

I am using nnDetection to detect pulmonary embolisms. While processing the label files, I noticed that many bounding boxes overlap, resulting in a final object count lower than what was indicated in the original label files. Is there any good solution to address this issue?

Additionally, what happens when nnDetection encounters an incomplete square bounding box (e.g., a box with a missing corner, possibly due to overlap with another bounding box)?

Thank you!

**Comment by mibaumgartner** [comment]
Dear @ZHUJJFDU ,

to support a broad range of annotation styles we have decided to map everything to segmentations masks to unify their representation. Typically this is not a problem since voxels in 3D can only be occupied by a single object. 

Some approaches: 
- instead of using bounding box masks, use spherical masks to encode the embolisms. Usually objects tend to be roundish and do not extend towards the corners of bounding boxes
- start with the largest structures and progress to the smaller ones while adding the bounding boxes. This will avoid overwriting small strucutres with big ones and avoids that they might be missing later 

nnDetection derives the bounding boxes from the segmentation (by simply checking for the maximum extend along a given axis), if only the corner is missing nothing will happen. If an entire part of the object is missing than the resulting box will be smaller since the maximal extend in that direction is likely changed.
