### ISSUE TITLE
[Question] Convert 3D bounding box annotations to segmentations

### ISSUE THREAD

**Issue by Ellen-DUAN** [MIC-DKFZ/nnDetection#29]
Hi, I am trying to try nnDetection on Task_010 Colon from http://medicaldecathlon.com/ with my own 3D bounding box annotations. I have read issue#16 where you mentioned that **nndet_boxes2nii** converts boxes to a segmentation nifty file, but I couldn't find nndet_boxes2nii in this repo. Could you point out where it is? Thanks.

**Comment by mibaumgartner** [comment]
Hi @Ellen-DUAN ,

`nndet_boxes2nii` is only(!) intended for visualization purposes, please don't use it for any conversion scripts.

Since external bounding box formats can vary quite a bit (zero vs one indexed boxes, handling of object borders, clipping at image borders, ...) nnDetection does not provide a prebuild function for that (and it is a bit hacky 😅 )

Best,
Michael

**Comment by Ellen-DUAN** [comment]
Hey @mibaumgartner, thanks for your reply. I am wondering if manually creating rectangle segmentations from my bounding box annotations work?

**Comment by mibaumgartner** [comment]
Hi @Ellen-DUAN ,

While it is a bit hacky it should work (for tumors I typically use circles). Not sure how beneficial the segmentation part of RetinaU-net is in those cases, though (would need some testing :) )

Note that generally (probably not for colon), boxes can overlap while segmentations can not, so be careful when converting them :)

Best,
Michael
