### ISSUE TITLE
[Question] How to set the gpu id to use?

### ISSUE THREAD

**Issue by ZheMin-1992** [MIC-DKFZ/nnDetection#32]
Hi, in nnunet, use `CUDA_VISIBLE_DEVICES=1 nnUNet_train ....` can set which gpu to use in the training process.
Have tried this in nnDetection, seems not working. 
Currently is there a mechanism to set the preferred gpu id in a multi-gpu machine to use in the nnDetection?
Thanks!

**Comment by mibaumgartner** [comment]
Hi @ZheMin-1992 ,

sorry for the delay.
There is no explicit way of setting the GPU id because `CUDA_VISIBLE_DEVICES=1 nndet_train ...` works correctly on my workstation and in multiple cluster environments.

The Id could be changed here:
https://github.com/MIC-DKFZ/nnDetection/blob/a53f4fc72b3a20c8c32f688eb50522c16bd89d4d/scripts/train.py#L270

Best,
Michael
