### ISSUE TITLE
[Question]about inference

### ISSUE THREAD

**Issue by YuqingCai0316** [MIC-DKFZ/nnDetection#33]
Hello！
 where is the result folder after inference，I only found a 'pkl' file, 
isn't there a nifti file？

**Comment by mibaumgartner** [comment]
Hi @YuqingCai0316 ,

the predictions are located in `val_predictions` in the model folder and saved as pkl since it contains the predicted box coordiantes, probabilities and classes.

`nndet_boxes2nii `  can be used to convert the boxes to nifty for **visualization purposes only**. The visualization is only a simplification of the actual output.

Best,
Michael

**Comment by YuqingCai0316** [comment]
Hi! @mibaumgartner 
Thanks you for your reply. I've turned boxes into nifti, but I'm confused that  my training set is the focus of semantic segmentation. Why are the inference results rectangular boxes？

**Comment by mibaumgartner** [comment]
Hi @YuqingCai0316,

if you are looking for semantic segmentation you are in the wrong repository, you are looking for this one: https://github.com/MIC-DKFZ/nnUNet

This repository is about object detection where the output is a box (the semantic segmentation is used as an auxiliary task here).

Best,
Michael
