### ISSUE TITLE
[Question] Is it possible to use model with only one fold executed?

### ISSUE THREAD

**Issue by GabrielaProszczuk** [MIC-DKFZ/nnDetection#46]
I am aware it might have lower accuracy, but is it possible to predict on such model? Or are there some restrictions that need me to run all 5 folds?

**Comment by mibaumgartner** [comment]
Dear @GabrielaProszczuk ,

yes it is possible to run inference with a single model. Here are some things to keep in mind:
- As you already mentioned, the performance will be worse since ensembling usually gives quite a substantial boost.
- `nndet_predict` uses all models which are present in the training directory. Since the best and the last model are saved for each fold, the script would ensemble both of them. One simple solution is to copy the best model to a different directory (normally the last model is used for consolidation and the ensembled predictions)
- the hyperparameter optimization (`--sweep`) is only computed on the validation of that specific fold. As a result, they might be more unstable than optimizing it over all the folds (usually performed during consolidation)

Best,
Michael
