### ISSUE TITLE
What's kind of data augmentation supported[Question]

### ISSUE THREAD

**Issue by Derekabc** [MIC-DKFZ/nnDetection#54]
### :question: Question

Dear authors, I want to know does the current framework support any data augmentation, such as rotation, flip? Thank you for your time and any insights!

**Comment by mibaumgartner** [comment]
Dear @Derekabc ,

we use [Batchgenerators](https://github.com/MIC-DKFZ/batchgenerators) for our augmentations. It provides various transformations such as Rotation, Mirror etc.

Our exact augmentation pipeline can be found here: https://github.com/MIC-DKFZ/nnDetection/blob/6ac7dac6fd9ffd85b74682a2f565e0028305c2c0/nndet/io/augmentation/bg_aug.py#L193-L284

And its configuration: https://github.com/MIC-DKFZ/nnDetection/blob/6ac7dac6fd9ffd85b74682a2f565e0028305c2c0/nndet/conf/train/augmentation/base_more.yaml#L1-L46

Best,
Michael

**Comment by Derekabc** [comment]
Hi, @mibaumgartner thank you for your quick response! Your provided information is really helpful.

I am working on the LANA16 dataset and found that there are massive false positives that are actually vessels. However, intuitively I think the model can prevent this kind of case since vessels have distinguishable features in the Z direction, i.e., like a tree instead of spheres. 

My first thought is to increase the anchor size in the Z direction while I found the anchor size is big enough? (are the units for anchors pixels?)
![image](https://user-images.githubusercontent.com/25771207/156372854-e31c191a-a392-4618-bcf4-83664cc49a89.png)

Then I hope data augmentation may be helpful. While I think there are already some data augmentations supported?
![image](https://user-images.githubusercontent.com/25771207/156373302-8e4c2c40-adc8-483d-ba5a-a257d8181fef.png)

DO you have any ideas how to remove these false positives having apparent features (i.e., vessels)

Thank you so much for your time and help!

**Comment by mibaumgartner** [comment]
Dear @Derekabc ,

I'm not sure if increasing the size of the anchors in the z-direction would really help since it doesn't promote some kind of feature fusion along that direction. The out-of-the-box augmentation pipeline is quite extensive and worked well across our pool of datasets (some datasets work better with less augmentation others require more due to heterogeneity). Since LUNA16 is not part of our training/validation pool, our experiments are usually based on LIDC where we distinguish two classes of nodules and is more heterogeneous which results in somewhat different "main problems" (even though Luna is a subset of LIDC).

Another publication to check out in this context is "3DFPN-HS2: 3D Feature Pyramid Network Based High Sensitivity and Specificity Pulmonary Nodule Detection" from Liu et al. which performed very well on LUNA16 and specifically looked into the issue you mentioned.

Best,
Michael

**Comment by Derekabc** [comment]
Dear @mibaumgartner Thank you for your insights and suggested paper.

I have read the paper you mentioned above. They pretrained the model with different rotations, 0, 90, 180, and 270 degrees. 
![image](https://user-images.githubusercontent.com/25771207/156825590-8d5f5c2d-9ef6-4739-a253-ddf7d2fc2153.png)

Following are the augmentation settings for nnDetection. I am wondering if I want to try different rotation settings. 
![image](https://user-images.githubusercontent.com/25771207/156825763-9dd45bc8-22f8-491b-9a5e-1f30bc46a137.png)

Is it ok to implement it like 
```
 p_rot: 1 
 do_rotation: True 
 rotation_x: [-270, -180, -90, 0, 90, 180, 270] 
 rotation_y: [-270, -180, -90, 0, 90, 180, 270] 
 rotation_z: [-270, -180, -90, 0, 90, 180, 270] 
```
How about the probability p_rot, does it control the probability for the rotation to happen? **I really appreciate your time!**

**Comment by mibaumgartner** [comment]
Dear @Derekabc ,

you are looking for the `Rot90Transform` from batchgenerators. The pasted code snippet won't work since the nnDet config defines a lower and upper bound of the rotation (the angle is randomly sampled from that range).

Just note that I didn't recommend that paper for its augmentation but for its False Positive Reduction Stage.

Best,
Michael

**Comment by mibaumgartner** [comment]
I'll close the Issue for now but if any other questions arise please feel free to reopen the Issue.
