### ISSUE TITLE
How to run with only bound box(cube) annotation?[Question]

### ISSUE THREAD

**Issue by alibool** [MIC-DKFZ/nnDetection#56]

**Comment by mibaumgartner** [comment]
Dear @alibool ,

training with bounding box annotatins is currently not supported in a straight forward vashion (we hope to tackle that in a future update). Currently, the best way to achieve what you are looking for is to convert the bounding boxes into segmentation. One downside of this approach is that segmentations can not overlap while bonding boxes can. Nevertheless, many datasets will work just fine with this approach (as long as their ground truth boxes do not overlap which is the case for most 3D medical datasets).

If you know some better heuristics, e.g. Tumors are usually roundish, so circles or ellipsoids can be an even better alternative (we used circles for LUNA experiments).

Best,
Michael

**Comment by alibool** [comment]
@mibaumgartner Thanks for your reply, I have successfully created a RetinaNet from your implementation which can accept only bounding boxes as training targets, but the data loading process has to be reimplemented from scratch, I will update  in this issue and share my implementation if I finish all the procedure.

**Comment by mibaumgartner** [comment]
Dear @alibool ,

thanks for the udpate! The main reason it is not yet integrated, are the augmentations where the different representations induce various dis-/advantages e.g. bounding boxes are somewhat difficult to rotate due to the loss of localization while the commonly found center point + radius annotation can be rotated easily. Segmentations were the only representation where this could be modelled in a somewhat general way.

Best,
Michael
