### ISSUE TITLE
[Question]Issue with installation

### ISSUE THREAD

**Issue by RoqueRouteiral** [MIC-DKFZ/nnDetection#58]
### :question: Question
Hello,
I have been trying to install the nnDetection. I need to install from source as I do not have docker in my cluster or sudo rights. When installing from source and running the "test installation" line i get the following error.

python -c "import torch; import nndet._C; import nndet"

ImportError: /home/outeiral/nnDetection/nndet/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z8nms_cudaRKN2at6TensorES2_f

I looked for solutions in the internet and I saw this similar question: https://coder.social/MIC-DKFZ/nnDetection/issues/20
So I installed pytorch for using the cuda 10.2 but it didnt work either.

Is there something I am missing or that I could do?

To try to give more information, this is the output of my utils.py script:

![image](https://user-images.githubusercontent.com/22600009/158430337-a30ecae0-322f-492f-a3e0-b3da74e728cd.png)

Thank you in advance for the help.

**Comment by RoqueRouteiral** [comment]
Dear Michael,
Thank you for the quick answer.
Indeed, that was my first concern. However, when running torch.cuda.is_available() in python it returns "True". Also, I am running the nnUNet framework as well in the same cluster and it works without any issues. I assumed that the nvcc command was just failing because the path is not in the .bashrc file, but not because of CUDA not being installed. I checked in the documentation of my cluster and CUDA is installed. Shouldn't it be OK for the installation then?
Could it be due to something else?
Thank you again.
Best,
Roque

**Comment by RoqueRouteiral** [comment]
Dear @mibaumgartner,
As follow up I fixed the issue with the nvcc command but the error persists. Also I tried with CUDA 11.3.1 instead. The output of my utils.py now is shown below.
![image](https://user-images.githubusercontent.com/22600009/158547593-cef2f6f4-4ee2-418b-ac81-28164ba7537f.png)
Please let me know if you could think of another reason why it fails.
Best,
Roque

**Comment by mibaumgartner** [comment]
Dear Roque,

1) I'm not super familiar with the check torch performs with this function but Torch includes its own CUDA files (to make the installation easy and fast) so it is normal that it returns True (except the CPU only version is installed). 
2) In contrast to nnU-Net, nnDetection includes additional CUDA code which needs to be compiled during installation. This is why the installation process is more complex when compared to nnU-Net.
3) The env looks fine now, did you delete the `build` folder inside nnDetection when you re-installed? Otherwise, it will not recompile the code and the error persists even though the env is correct.

If the problem persists after deleting the build folder and reinstalling, please let me know. 

Best,
Michael

**Comment by mibaumgartner** [comment]
I added additional information about Common Installation Issues and how to debug them to the Readme, section `FAQ and Common Issues`. I will close the Issue for now but if you feel there is some information missing in the readme  / should be added to the readme, please feel free to reopen the Issue and I'll add the info to the readme as well.

Best,
Michael
