### ISSUE TITLE
[Question]Reproduce the results of RibFrac Task

### ISSUE THREAD

**Issue by carlinl** [MIC-DKFZ/nnDetection#6]
Hello

I was wondering what kinds of preprocessing methods did you use to get this mAP, like crop size and spacing? Thanks for your marvelous job by the way!

![image](https://user-images.githubusercontent.com/17608611/122890435-414b7d00-d376-11eb-9851-ea266f5703fa.png)

**Comment by mibaumgartner** [comment]
Hi @carlinl ,

you can check our [paper](https://arxiv.org/abs/2106.00817)(will be linked to the readme soon) for more info on how we came up with the hyperparameters.

RibFrac:
Target Spacing is [1.25, 0.73, 0.73] and patch size during training is [112 160 160] with batch size 4. These settings will work on GPUs with 11GB of VRAM (e.g. RTX 2080TI).

Please note that our numbers are not directly comparable to the live leaderboard due to several reasons:
- the reported numbers are Box mAP at an IoU of 0.1 while the official challenge is an Instance Segmentation Task with FROC and an IoU of 0.25. (in case you rerun our experiment and check the FROC score reported by nnDet, note that the False Positive thresholds between nnDet and the challenge are different)
- we used a 5 fold cross-validation scheme for the numbers.

Best,
Michael

**Comment by carlinl** [comment]
Thanks for your reply, it helps a lot!

**Comment by BelieferQAQ** [comment]
> 



> Thanks for your reply, it helps a lot!
Hello, how long does it take you to train a round? Why do I need about 4 hours? 3090ti. Can you add a QQ for discussion. three hundred and eighteen million eight hundred and thirty-one thousand four hundred and eighteen

**Comment by BelieferQAQ** [comment]
> Thanks for your reply, it helps a lot!

Hello, how long does it take you to train a round? Why do I need about 4 hours? 3090ti. Can you add a QQ for discussion.318831418

**Comment by BelieferQAQ** [comment]
> 
Hello, my target spacing, patch size and batch size are the same as yours. The GPU is 24GB (3090ti). It takes more than 3 hours to train an epoch. Is it normal? How long will you train?

**Comment by BelieferQAQ** [comment]
> Hi @carlinl ,
> 
> you can check our [paper](https://arxiv.org/abs/2106.00817)(will be linked to the readme soon) for more info on how we came up with the hyperparameters and the whole preprocessing/training/inference pipeline.
> 
> RibFrac: Target Spacing is [1.25, 0.73, 0.73] and the patch size is [112 160 160] with batch size 4. These settings will work on GPUs with 11GB of VRAM (e.g. RTX 2080TI).
> 
> Please note that our numbers are not directly comparable to the live leaderboard due to several reasons:
> 
> * the reported numbers are Box mAP at an IoU of 0.1 while the official challenge is an Instance Segmentation Task with FROC and an IoU of 0.25. (in case you rerun our experiment and check the FROC score reported by nnDet, note that the False Positive thresholds between nnDet and the challenge are different)
> * we used a 5 fold cross-validation scheme for the numbers.
> 
> Best, Michael

Hello, my target spacing, patch size and batch size are the same as yours. The GPU is 24GB (3090ti). It takes more than 3 hours to train an epoch. Is it normal? How long will you train?

**Comment by mibaumgartner** [comment]
Continued in https://github.com/MIC-DKFZ/nnDetection/issues/102
