### ISSUE TITLE
[Question] Lightning Deprecation Warning

### ISSUE THREAD

**Issue by DSRajesh** [MIC-DKFZ/nnDetection#66]
### :question: Question

I am getting this error log during a docker image execution "/venv/lib/python3.8/site-packages/pytorch_lightning/core/memory.py:16: LightningDeprecationWarning: pytorch_lightning.core.memory.get_memory_profile and pytorch_lightning.core.memory.get_gpu_memory_map have been moved to pytorch_lightning.utilities.memory since v1.5 and will be removed in v1.7. rank_zero_deprecation( " and one of the solutions suggested is to use the functions of "warnings" python module but "pip install warnings" was not successful. Can any one please tell how to get rid of this "lightning depracation" warning

**Comment by mibaumgartner** [comment]
Dear @DSRajesh ,

I lowered the version of nevergrad which lead to an pip error due to incompatible numpy versions. This should be unrelated to that. Since the error mentions `lightning v1.5` und nndet is limited to `pytorch_lightning>=1.3.1,<=1.4.2` I think you probably have the wrong version installed. (I was not able to reproduce your error with described build in the readme).

So resolve this, I need more info on your env such as the pytorch and pytorch-lightning version.

Best,
Michael

**Comment by tejavu** [comment]
The Dataset only trains for 59 Epochs and I get this error
Epoch 59: 100%|████████████████████████████████████████████| 2600/2600 [28:24<00:00,  1.53it/s, loss=-0.938, v_num=4e06]                                                                                           /opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/deprecated_api.py:32: LightningDeprecationWarning: `Trainer.train_loop` has been renamed to `Trainer.fit_loop` and will be removed in v1.6.
  rank_zero_deprecation(
This is the result of nndet_env

![image](https://user-images.githubusercontent.com/100778166/165324931-5dbe3ca1-5f1f-42a6-9980-1820b63a6703.png)

everything else was installed based on the requirements.txt

**Comment by DSRajesh** [comment]
Dear  @mibaumgartner 

Here are the details of our run

RUN pip install torch==1.12.0.dev20220213+cu113 -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html
RUN pip install torchvision==0.13.0.dev20220213+cu113 -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html 
RUN pip install torchmetrics==0.7.0 pytorch-lightning==1.5.9

Also we had used the module for nodule prediction.

Thanks
Rajesh

**Comment by mibaumgartner** [comment]
Dear @DSRajesh ,

I'm a bit surprised that pip did not complain about the versions since nnDetection is limited to `pytorch_lightning>=1.3.1,<=1.4.2` (I did not test nndet with pt 1.12 dev so I can not comment on problems which may arise due to that version). You may want to consider to downgrade the lightning version. If it only remains a warning it might be fine for now though.
