### ISSUE TITLE
 [Question] Time to perfection on the image segmentation component

### ISSUE THREAD

**Issue by nengwp** [MIC-DKFZ/nnDetection#69]
### :question: Question

Very nice project.
I want to understand the effect of image segmentation and compare with nnUNet, but output mask is not supported yet.

**Comment by mibaumgartner** [comment]
Dear @nengwp ,

our work is based on Retina U-Net (https://arxiv.org/abs/1811.08661) which leverages the segmentations  as an additional auxiliary signal for training but we are actually not interested in the segmentation performance. As a result, all of our experiments focussed on the detection performance and we rarely looked at the segmentation performance (even though they looked decent in a qualitative analysis). 
Instance Segmentation which would the better comparison against nnU-Net is not supported as of right now. 

Since the other Issue specifically mentioned LUNA16, note that LUNA16 only includes Center Point + Radius information and we generated Circle Masks from it in order to train Retina U-Net -> the generated segmentations will be circles as well and not "real" lesion segmentations. 

Best,
Michael

**Comment by nengwp** [comment]
**Thank you very much for your answer

This time was consulted due to the documentation mentioning that future versions may include an option for image segmentation.

Also, I'm implementing other tasks with lesion annotation, not LUNA16. I'm interested in segmentation and classification, but I'm looking to remove background areas. Therefore, detection is used as an intermediate component, but unfortunately, the false positives and false positives caused by detection are very serious.

Thank you again for your care and enthusiasm!**

**Comment by mibaumgartner** [comment]
Dear @nengwp ,

the performance of the detection part is quite dependent on the task and (In my opinion) still poses a very difficult problem in general. When looking at the FROC curves from LUNA16 the performance usually seems quite optimistic because there is a very long list of "ignored" positions and thus False positives are lower than usual, e.g. when looking at RibFrac the performance drops significantly towards low number of FPs (in the official paper as well). Ribfrac is just an example here, but there are many other publications for this and is also reflected in my own experiments (this is especially true in CT scans where the imaging area is usually quite large and different for modalities which have lower spatial resolution). 

Best,
Michael

**Comment by nengwp** [comment]
Hi @mibaumgartner 

Thank you very much for your answer, I will close this question.

**Comment by nengwp** [comment]
Hi @mibaumgartner 

Thank you very much for your answer.
