### ISSUE TITLE
Where to incorporate a register_full_backward_hook?

### ISSUE THREAD

**Issue by rooskraaijveld** [MIC-DKFZ/nnDetection#76]
Hi, I am trying to incorporate a backward hook into nnDetection and I was wondering where you would suggest to put it? So far, I have completed several attempts in the predictor.py file, but it doesn't seem to fire. Do you have a suggestion? :)

**Comment by mibaumgartner** [comment]
Dear @rooskraaijveld ,

the predictor is only used for inference of the patients and thus there is not backward pass. You could either register it in the ptmodule (https://github.com/MIC-DKFZ/nnDetection/blob/main/nndet/ptmodule/retinaunet/base.py) or in the model itself (https://github.com/MIC-DKFZ/nnDetection/blob/main/nndet/core/retina.py). The lightning module (ptmodule) might be preferable since it has access to all the individual components and is responsible for building them.

Best,
Michael

**Comment by rooskraaijveld** [comment]
Dear Michael,

Thank you so much for you answer. 

I am trying to implement the following code in nnDetection:

  ```
model.eval()
    for ind, (img, label) in enumerate(loader):
            img = img.to(device, dtype=torch.float)
            output = model(img)
            activation_layer = activation[L].to(device, dtype=torch.float)

            activation_layer.register_hook(activation_layer.grad)
            logit = output[:,1]
            gradients = torch.autograd.grad(logit, activation_layer, retain_graph=True)[0]
            grad = gradients.cpu().detach().numpy()
```

The code above is for a classifier, and as you can see, both a forward and backward hook are used. 

I have been trying to implement this for nnDetection, both in the base.py and retina.py model but it doesn't seem to be working (of course I altered the code to fit the code of nnDetection). It might be a bit too much to ask, but do you have a suggestion on how to do this? Is using a forward and backward hook in the base/retina.py files possible? 

I really appreciate your help. Thanks in advance :)

**Comment by rooskraaijveld** [comment]
Dear Michael,

Thank you! It worked in the retina.py file!

**Comment by mibaumgartner** [comment]
Great to hear, thanks for the update! I'll close the Issue for now but if anything else comes up please reopen (if the same) or open a new one.
