### ISSUE TITLE
[Question] Directories and files used

### ISSUE THREAD

**Issue by aldemirfilho** [MIC-DKFZ/nnDetection#86]
### :question: Question

Doubt part 1:

hello, could you help me to confirm the path of the files?

I'm working with Luna's base, and from what I've noticed, the path to my files would be:
opt/data/Task016_Luna/raw

right?

-------------------------
Doubt part 2:

The other question is about the use of the following files:

annotations.csv,
candidates.csv,
candidates_V2.zip,
evaluationScript.zip,
sampleSubmission.csv,
seg-lungs-LUNA16.zip,

These files are at the base of Luna, but I was in doubt if they are used and in which directory they are placed.

In addition to all these files, there are subsets, that goes from 0 to 9, and from what I have understood these goes in opt/data/Task016_Luna/raw

Is it right?

If possible, could you help me?
 I look forward to hearing from you about the support on these points 
 
Thank you very much!

**Comment by mibaumgartner** [comment]
Dear @aldemirfilho ,

yes the paths should be correct (the script will automatically check that the paths exist and will raise Errors otherwise). The `annotations.csv` needs to be placed into the raw directory to generate the masks.

Apart from the data / annotations, the evaluationScript will be needed in the end to compute the FROC according to the LUNA guidelines, i.e. there is a list of candidates positions which will be ignored (neither count as True Positive nor False False Positives) during evaluation (nnDetection does not include these ignore positions, so the scores computed by it will be lower than the official score computed via the provided script). 

Best,
Michael

**Comment by aldemirfilho** [comment]
Thank you so much! I will try this.

Aldemir Melo.
