### ISSUE TITLE
Nvidia cuda vs Conda cuda

### ISSUE THREAD

**Issue by vankhoa21991** [MIC-DKFZ/nnDetection#9]
Hi, why do this library requires cuda installed on the machine, and not use the cuda installed on anaconda?

**Comment by mibaumgartner** [comment]
Hi,

nndet uses `CUDAExtension` from PyTorch to build the CUDA code in this repository. According to [this](https://stackoverflow.com/questions/56470424/nvcc-missing-when-installing-cudatoolkit) the conda package only contains a subset of the official CUDA installation. E.g. it does not provide the nvcc compiler that will be used to compile the CUDA code (there is a [guide from pytorch](https://pytorch.org/tutorials/advanced/cpp_extension.html?highlight=cuda)). 

Best,
Michael

**Comment by vankhoa21991** [comment]
Thanks for your answer, this means that in a cluster where no nvidia cuda is installed (only conda cuda), the code can not be compiled?

**Comment by mibaumgartner** [comment]
At least I'm not aware of a way to use it with conda cuda right now, sorry. Generally speaking, the docker setup of nnDetection is probably the most straightforward one since it already packs all the CUDA requirements and only requires compatible Nvidia GPU drivers (requires docker support on the cluster though).
