### ISSUE TITLE
[Question]Can I not use the 5 cross-validation?

### ISSUE THREAD

**Issue by LWHYC** [MIC-DKFZ/nnDetection#92]
### :question: Question

Hi!
Since my training set is very small, can I not use cross-validation?

**Comment by mibaumgartner** [comment]
Dear @LWHYC ,

yes, it is possible to skip the cross-validation by defining a manual data split (nndet_consolidate is only needed if more than one fold is trained). In general, I would stick to the cross-validation scheme since the ensembling of a diverse set of models is usually quite strong during test time.

Best,
Michael
